src/Entity/Superheros.php
<?php

namespace App\Entity;

use App\Repository\SuperherosRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SuperherosRepository::class)
 */
class Superheros
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nickname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $real_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $origin_description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $catch_phrase;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $images;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $superpowers;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(string $nickname): self
    {
        $this->nickname = $nickname;

        return $this;
    }

    public function getRealName(): ?string
    {
        return $this->real_name;
    }

    public function setRealName(string $real_name): self
    {
        $this->real_name = $real_name;

        return $this;
    }

    public function getOriginDescription(): ?string
    {
        return $this->origin_description;
    }

    public function setOriginDescription(string $origin_description): self
    {
        $this->origin_description = $origin_description;

        return $this;
    }

    public function getCatchPhrase(): ?string
    {
        return $this->catch_phrase;
    }

    public function setCatchPhrase(string $catch_phrase): self
    {
        $this->catch_phrase = $catch_phrase;

        return $this;
    }

    public function getImages(): ?string
    {
        return '/uploads/'.$this->images;
    }

    public function setImages(string $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getSuperpowers(): ?string
    {
        return $this->superpowers;
    }

    public function setSuperpowers(string $superpowers): self
    {
        $this->superpowers = $superpowers;

        return $this;
    }
}

src/Form/SuperherosType.php
<?php

namespace App\Form;

use App\Entity\Superheros;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class SuperherosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nickname')
            ->add('real_name')
            ->add('origin_description')
            ->add('superpowers')
            ->add('catch_phrase')
            ->add('imagesFile', FileType::class, [
                'mapped' => false,
                'constraints' => [
                    new Image(),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Superheros::class,
        ]);
    }
}

src/Controller/SuperherosController.php
<?php

namespace App\Controller;

use App\Entity\Superheros;
use App\Form\SuperherosType;
use App\Repository\SuperherosRepository;
use App\Services\UploadFile;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/superheros")
 */
class SuperherosController extends AbstractController
{
    /**
     * @Route("/", name="superheros_index", methods={"GET"})
     */
    public function index(Request $request, PaginatorInterface $paginator): Response
    {
//        return $this->render('superheros/index.html.twig', [
//            'superheros' => $superherosRepository->findAll(),
//        ]);
        $query = $this->getDoctrine()
            ->getRepository(Superheros::class)
            ->createQueryBuilder('c');

        $superhero = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            $request->getSession()->get('items', $request->query->get('items', 5))
        );

        return $this->render('superheros/index.html.twig', ['superheros' => $superhero]);

    }

    /**
     * @Route("/new", name="superheros_new", methods={"GET","POST"})
     */
    public function new(Request $request, UploadFile $uploadFile): Response
    {
        $superhero = new Superheros();
        $form = $this->createForm(SuperherosType::class, $superhero);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['imagesFile']->getData();
            $nameFile = $uploadFile->uploadImage($file);
            $superhero->setImages($nameFile);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($superhero);
            $entityManager->flush();

            return $this->redirectToRoute('superheros_index');
        }

        return $this->render('superheros/new.html.twig', [
            'superhero' => $superhero,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="superheros_show", methods={"GET"})
     */
    public function show(Superheros $superhero): Response
    {
        return $this->render('superheros/show.html.twig', [
            'superhero' => $superhero,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="superheros_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Superheros $superhero, UploadFile $uploadFile): Response
    {
        $form = $this->createForm(SuperherosType::class, $superhero);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['imagesFile']->getData();
            $nameFile = $uploadFile->uploadImage($file);
            $superhero->setImages($nameFile);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('superheros_index');
        }

        return $this->render('superheros/edit.html.twig', [
            'superhero' => $superhero,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="superheros_delete", methods={"POST"})
     */
    public function delete(Request $request, Superheros $superhero): Response
    {
        if ($this->isCsrfTokenValid('delete'.$superhero->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($superhero);
            $entityManager->flush();
        }

        return $this->redirectToRoute('superheros_index');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/superheros/_delete_form.html.twig
<form method="post" action="{{ path('superheros_delete', {'id': superhero.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ superhero.id) }}">
    <button class="btn">Delete</button>
</form>

templates/superheros/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/superheros/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Superheros{% endblock %}

{% block body %}
    <h1>Edit Superheros</h1>

    {{ include('superheros/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('superheros_index') }}">Main</a>

    {{ include('superheros/_delete_form.html.twig') }}
{% endblock %}

templates/superheros/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Superheros index{% endblock %}

{% block body %}
    <h1>Superheros index</h1>

    <table class="table" border="2">
        <thead>
            <tr>
                <td>Id</td>
                <td>Nickname</td>
                <td>Real_name</td>
                <td>Origin_description</td>
                <td>Superpowers</td>
                <td>Catch_phrase</td>
                <td>Images</td>
                <td>actions</td>
            </tr>
        </thead>
        <tbody>
        {% for superhero in superheros %}
            <tr>
                <td>{{ superhero.id }}</td>
                <td>{{ superhero.nickname }}</td>
                <td>{{ superhero.realName }}</td>
                <td>{{ superhero.originDescription }}</td>
                <td>{{ superhero.superpowers }}</td>
                <td>{{ superhero.catchPhrase }}</td>
                <td><img src="{{ superhero.images }}" style="max-width: 100px"></td>
                <td>
                    <a href="{{ path('superheros_show', {'id': superhero.id}) }}">show</a>
                    <a href="{{ path('superheros_edit', {'id': superhero.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
        <div class="navigation">
            {{ knp_pagination_render(superheros) }}
        </div>
    </table>

    <a href="{{ path('superheros_new') }}">Create new</a>
{% endblock %}

templates/superheros/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Superheros{% endblock %}

{% block body %}
    <h1>Create new Superheros</h1>

    {{ include('superheros/_form.html.twig') }}

    <a href="{{ path('superheros_index') }}">back to list</a>
{% endblock %}

templates/superheros/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Superheros{% endblock %}

{% block body %}
    <h1>Superheros</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ superhero.id }}</td>
            </tr>
            <tr>
                <th>Nickname</th>
                <td>{{ superhero.nickname }}</td>
            </tr>
            <tr>
                <th>Real_name</th>
                <td>{{ superhero.realName }}</td>
            </tr>
            <tr>
                <th>Origin_description</th>
                <td>{{ superhero.originDescription }}</td>
            </tr>
            <tr>
                <th>Catch_phrase</th>
                <td>{{ superhero.catchPhrase }}</td>
            </tr>
            <tr>
                <th>Superpowers</th>
                <td>{{ superhero.superpowers }}</td>
            </tr>
            <tr>
                <th>Images</th>
                <td><img src="{{ superhero.images }}" style="max-width: 300px"></td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('superheros_index') }}">back to list</a>

    <a href="{{ path('superheros_edit', {'id': superhero.id}) }}">edit</a>

    {{ include('superheros/_delete_form.html.twig') }}
{% endblock %}